### ISSUE TITLE
Check flags internally instead of "IsXEnabled/X()" pattern

### ISSUE THREAD

**Issue by tommck** [mbrit/MetroLog#26]
Instead of this code:

if (this.Log.IsInfoEnabled)
            this.Log.Info("I've been navigated to.");

It would be nice to be able to eliminate the "if"... since the "Log" knows its own flag, it's redundant to check and then call.

If you're trying to avoid computation with a non-trivial string setup, you can add an override that takes an expression (Func<string>) like this:

this.Log.Info(() => { 
   // ... expensive computational calls to generate the message
   return msg;
}).

This would allow the log to check the flag for itself and then decide whether or not to execute the lambda expression.

It would make client code much cleaner looking.

**Comment by benschi11** [comment]
I really would appreciate this changes. Are there anything speaking against it? Otherwise I will try to send an pull request?

**Comment by tommck** [comment]
I don't see anything wrong with it, but I suggested it 2 years ago.  Not sure if a pull request will help if he can't be bothered to even comment

**Comment by benschi11** [comment]
Ok! I checked the code and it should be there since 2012 :). See MetroLog/Internal/Logger.cs on line 103

```c#
if (!(targets.Any()))
  return EmptyOperations;
```
I tested it and it works. No output if there is no target configured with the corresponding level. I have no idea why it is different in the wiki!? Maybe it has a better performance if you check it at the app level?!?

**Comment by onovotny** [comment]
Sorry I've been very busy lately -- if someone wants to submit a PR, I can merge it in. @tommck I like your idea of providing an overload for a setup string; that was one of the original intents.

**Comment by tommck** [comment]
Unfortunately, I have not been developing on the platform for about 18 months at this point, so it's a bit difficult to implement that right now.  It shouldn't be too hard to implement though..

**Comment by benschi11** [comment]
Maybe I can try it. But I am not sure if I 100% understand your approach. Can you explain it in more detail? Still I have to getting familiar with the MetroLog source code as well.

**Comment by tommck** [comment]
Sure.

First, internalize the flag check so it's not done from outside (if needed).

Second, add an overloaded method that takes an Action<string> method.  Then, this checks the necessary flag and _then_ it calls the Action() to get the string to log (this allows you to avoid even doing complex string construction (StringBuilders, etc) unless it's really needed.  

I've had situations where I've had to do mathematical calculations in order to spit out meaningful log messages.  If you put it in the Action<string> and never call it, you never incur the cost of the calculations.

Let me know if you need more clarification.

Tom

**Comment by benschi11** [comment]
Thanks. Just for clarification:
Moving the check should be already done in the logger itself or do I miss something?
2) I need first to modify the ILogger interface and add an overload for the logging methods to accept an Action<string> method and invoke this action if there is a target. Am I correct?

**Comment by onovotny** [comment]
I need to verify .... I did think that the check is already being done and that the if( IsxxxEnabled) are just extras in case you want to prevent an expensive call to .log. If that's true, is this even necessary? Just call .Log if perf isn't a concern there then.

**Comment by tommck** [comment]
I think the modifications for 2) are what you say they are @benschi11

**Comment by onovotny** [comment]
Closing for now, please reopen if there's still an issue.
