### ISSUE TITLE
No GlobalCrashHandler equivalent for WinJS

### ISSUE THREAD

**Issue by tommck** [mbrit/MetroLog#39]
The GlobalCrashHandler class assumes you're using a XAML-based application, so I wanted to roll my own to handle the same situation for WinJS.  Unfortunately, the LazyFlushManager is internal and so is the GetTargets method on the LoggingConfiguration.

So, I can't figure out how to make sure that all the messages are flushed before the app exits.

**Comment by onovotny** [comment]
Closing for now. Will re-open if needed. Seems like WinJS usage is pretty low?
