### ISSUE TITLE
LogManagerFactory.CreateLogManager(loggingConfiguration) generates FileLoadException and MissingMethodException on app start-up

### ISSUE THREAD

**Issue by aceportgas** [mbrit/MetroLog#46]
Hi, 

Using MetroLog v0.8.6 in the MSDN sample code (button effects.zip) below generates a FileLoadException and MissingMethodException:
-----------------------------------------------------------------------------------------
http://code.msdn.microsoft.com/Button-Effects-by-Anwar-4dc1d97f
-----------------------------------------------------------------------------------------

An exception of type 'System.IO.FileLoadException' occurred in mscorlib.ni.dll and wasn't handled before a managed/native boundary
'TaskHost.exe' (CLR C:\windows\system32\coreclr.dll: Silverlight AppDomain): Loaded 'C:\windows\system32\en-US\mscorlib.debug.resources.dll'. Module was built without symbols.
An exception of type 'System.MissingMethodException' occurred in mscorlib.ni.dll and wasn't handled before a managed/native boundary
An exception of type 'System.MissingMethodException' occurred in mscorlib.ni.dll and wasn't handled before a managed/native boundary

------------------------------------------------------------------------------------------

Note: The sample code is a Windows Phone7 app. I converted it to Windows Phone 8 app then run it with MetroLog referenced. 

Here's the code I added to Application_Launching() method:

    ILogger log;
    LoggingConfiguration loggingConfiguration = new LoggingConfiguration();
    loggingConfiguration.IsEnabled = true;
    loggingConfiguration.AddTarget(LogLevel.Trace, LogLevel.Fatal, new DebugTarget());
    log = LogManagerFactory.CreateLogManager(loggingConfiguration).GetLogger<App>();

            
    log.Warn("Application_Launching");

At LogManagerFactory.CreateLogManager(loggingConfiguration), the exceptions are generated. Is this a known issue? If yes, when will it be fixed? I can reproduce this exception on MetroLog v0.8.6. Did I miss anything that should be included?

This does not cause the application to crash but it would be good to know why this happens and if poses a risk on the application using the logger.

**Comment by onovotny** [comment]
These are by design due to probing for the platform assembly.
