### ISSUE TITLE
 'MetroLog.ILogger', which is not a valid Windows Runtime type

### ISSUE THREAD

**Issue by maxindahouze** [mbrit/MetroLog#55]
Try to use in background task WP 8.1
Method 'LiveTileAgent.LiveTileBackgroundTask.Log.get()' returns 'MetroLog.ILogger', which is not a valid Windows Runtime type.  Methods exposed to Windows Runtime must return only Windows Runtime types.

**Comment by mkamonster** [comment]
Looks like you try to expose ILogger as a public property of the BackgroundTask, why don't keep it internal? That's what I'm doing.

**Comment by onovotny** [comment]
Closing for now, please re-open if this is still an issue.
