### ISSUE TITLE
Is MetroLog PCL compatible?

### ISSUE THREAD

**Issue by jesusgarza** [mbrit/MetroLog#61]
I am trying to install MetroLog on a Xamarin.Forms project. It does install on the iOS and Android projects, but not on the PCL Project. I get this:

>Could not install package 'MetroLog 0.8.7.1'. You are trying to install this package into a project that 
>targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', 
>but the package does not contain any assembly references or content files that are compatible with 
>that framework. For more information, contact the package author.

Any ideas?

**Comment by onovotny** [comment]
In your PCL project, what are the selected frameworks?

**Comment by Sohra** [comment]
Just a guess, but I bet he's using Profile 111, which supports the widest range of platforms (iOS, Android, Windows Phone, Windows 8, and .NET 4.5).  I was using this too in MetroLog 0.8.6.1, but that profile was removed in 0.8.7.1 - replaced with 259 which is Windows RT only platforms.  It's a real shame to lose that profile in MetroLog.

**Comment by jesusgarza** [comment]
Its a Xamarin Forms project, so its PCL 4.5 (Profile 78).

**Comment by onovotny** [comment]
The fix for this should be easy - just update the PCL to use Windows 8.1 instead of 8. VS 2015 is unable to open Win8 projects (forces update to 8.1), so there's no real choice. Also, most apps are targeting 8.1+ as the Win8.0 market share is practically non-existent at this point.

**Comment by jesusgarza** [comment]
Thanks for your answer Oren. Sorry for not being clear, I am developing a
Xamarin Forms project for iOS and Android with Xamarin Studio on a Mac.

**Comment by onovotny** [comment]
That may be but the portable library still specifies a set of targeted platforms. If you don't need Windows 8 at all, you should uncheck it completely.

**Comment by jesusgarza** [comment]
OK, thanks Oren.

Best regards.

**Comment by beadn** [comment]
I am trying to install MetroLog on a PCL (Profile 78) and I cannot install it.

"Could not install package 'MetroLog 0.8.9'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

 this PCL should work in Android, iOS, and Windows Phone. Should I use another library? What is wrong?

**Comment by Jamizzle93** [comment]
I am having a very similar problem to beadn.
I'm trying to install MetroLog with PCL 4.5 - Profile259 and cannot.

The error I receive is:
"Could not install package 'MetroLog 0.8.9'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by alvinmeimoun** [comment]
Same problem with these targets 'portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10'

**Comment by onovotny** [comment]
MetroLog does require Win8.1+. Those PCL profiles are win8, which is causing the conflict. Can you try using a different PCL profile that includes Win8.1 instead of win8?

**Comment by onovotny** [comment]
This should be fixed in 0.9.0

**Comment by alvinmeimoun** [comment]
It is not possible to set to Windows 8.1, Visual Studio 2013 automatically reset it to Win 8.0 with a message like "API are same". So I'll wait for version 0.9.0 and I will test again
