### ISSUE TITLE
MetroLog 0.8.7.1 from NuGet has "WindowsRuntime 1.4" metadata, fails certification in Windows Store

### ISSUE THREAD

**Issue by PaulosV** [mbrit/MetroLog#62]
The NuGet version of MetroLog 0.8.7.1 has an incorrect "WindowsRuntime 1.4" runtime version for MetroLog.WinRT assembly, even though it works just fine on Windows 8.1 and Windows Phone 8.1.
This results in failed technical validation in WACK 3.4 and Windows Store.

Was the assembly compiled with Visual Studio 2015 CTP5?
Supposed solution is to either upgrade to VS2015 RC or compile it using VS2013 with the latest update.

```
   General metadata correctness test

   Error Found: The general metadata correctness test detected the
following errors:
       Winmd file C:\Program
Files\WindowsApps\SomeAppOfMine_1.1.0.4_x64__3zae6qkyg7m0g\MetroLog.WinRT.winmd
is missing "WindowsRuntime 1.3" or "WindowsRuntime 1.2" in its version
string. The version string in the file is "WindowsRuntime 1.4;CLR
v4.0.30319".
   Impact if not fixed: Windows store doesn't allow apps that don't
pass Windows Runtime Metadata Validation.
   How to fix: Please ensure that the compiler you are using to
generate your Windows Runtime types is up to date with with the Windows
Runtime specifications.
```

For now I've "resolved" my issue using version 0.8.6.1.

**Comment by onovotny** [comment]
I just rebuilt it with VS 2015 RC, can you try again (version 0.8.8)?

**Comment by PaulosV** [comment]
Ok, seems like it should work now, runtime version is WindowsRuntime 1.3;CLR v4.0.30319. I'll do the WACK and then if it passes, I'ľl close it? :)

**Comment by PaulosV** [comment]
Okay, WACK 3.4 passed :+1: thanks :) closing
