### ISSUE TITLE
Unable to upgrade to 0.8.9

### ISSUE THREAD

**Issue by pwillies** [mbrit/MetroLog#66]
I'm trying to upgrade from MetroLog 0.8.6 to the latest version 0.8.9. However, the MetroLog targets seem to have changed and that is creating a problem for me on a couple of my own PCL's. I get this error:

> Could not install package 'MetroLog 0.8.9'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Here's what 0.8.6 reports as targets:
> .NET 4.5, .NET Core 4.5 (Windows Store apps), Windows Phone 8, WinPhone 8.1 and WinJS

Here's what 0.8.9 reports as targets:
> .NET 4.5, Windows 8.1 (Windows Store apps), Windows Phone 8, WinPhone 8.1 WinJS, Xamarin.iOS, Xamarin.Android.

My own project targets:
> 'portable45-net45+win8+wpa81'

I've tried to update the build targets for my own project, but it seems like it's already up-to-date. Is it possible 0.8.9 went backwards? Any ideas how I can get my project onto the latest MetroLog version?

Thanks,
Paul

**Comment by onovotny** [comment]
So Win8 support was dropped as VS 2015 forces that. Can you try changing your supported frameworks in your PCL to Win8.1+?

**Comment by onovotny** [comment]
Closing for now. Please reopen if this is still an issue.
