### ISSUE TITLE
Use of .NET Native Tool chain (required for Windows 10 UWP store) throws System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by TrevorBarstowMobile5** [mbrit/MetroLog#68]
Are there any tests for Windows OS version in MetroLog which might fail for UWP? 
MetroLog has been working fine under Windows 8.1 and Windows 10. The app is being ported to Universal Windows app and when we turned on .NET Native tool chain build option, which is required for store submission, we get the following exceptions
Exception thrown: 'System.PlatformNotSupportedException' in MetroLog.dll
Exception thrown: 'System.TypeInitializationException' in System.Private.CoreLib.dll
An exception of type 'System.TypeInitializationException' occurred in System.Private.CoreLib.dll but was not handled in user code
Additional information: TypeInitialization_Type_NoTypeAvailable

**Comment by onovotny** [comment]
There's no known issues with .NET Native with MetroLog. I've been using it on a Win10 store project since July without any issues (including when compiled as .NET Native). 

What does your project structure look like; what are the projects in it and which ones reference MetroLog?

**Comment by TrevorBarstowMobile5** [comment]
That's useful information.

MetroLog is being used in conjunction with HockeySDK (provides remote
access to crash logs) which needs a logger with ILogger interface. The
exception in MetroLog is being thrown when the HockeySDK is being
configured.

Project structure is

App (Universal Windows)
- ref Library1 (Universal Windows)
       - ref MetroLog
       - ref MetroLog Targets
       - ref Library 2
- ref Library 2 (Universal Windows)

The project.json dependencies show versions
    "MetroLog": "0.8.9",
    "MetroLog.Targets": "1.0.0",


On 12 October 2015 at 13:21, Oren Novotny <notifications@github.com> wrote:

> There's no known issues with .NET Native with MetroLog. I've been using it
> on a Win10 store project since July without any issues (including when
> compiled as .NET Native).
>
> What does your project structure look like; what are the projects in it
> and which ones reference MetroLog?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbrit/MetroLog/issues/68#issuecomment-147379776>.
>



-- 

Trevor Barstow

[image: Mobile5 Media Ltd] <http://mobile-5.com/>

Mobile5 Media Ltd
16 Dufour's Place, W1F 7SP
t: +44 (0)1234 567891
m: +44 (0)1234 567891
Skype: mobile5.trevor.barstow
http://mobile-5.com

[image: Mobile5 Media Ltd]  <https://twitter.com/mobilefive>[image: Mobile5
Media Ltd]  <https://www.linkedin.com/company/mobile5-media-limited>[image:
Mobile5 Media Ltd] <https://www.facebook.com/mobile5media>


This e-mail and any accompanying attachments are intended only to be read
or used by the named addressee(s). It is confidential and contains legally
privileged information. If you have received this message in error, please
notify the sender immediately and delete this message.

**Comment by onovotny** [comment]
Have you tried adding a MetroLog reference directly to the app project in addition to the library? NuGet could be missing a file reference when it's copying stuff over.

**Comment by TrevorBarstowMobile5** [comment]
Adding MetroLog reference to the main app project had no effect. Any other
ideas?

On 12 October 2015 at 14:07, Oren Novotny <notifications@github.com> wrote:

> Have you tried adding a MetroLog reference directly to the app project in
> addition to the library? NuGet could be missing a file reference when it's
> copying stuff over.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbrit/MetroLog/issues/68#issuecomment-147393895>.
>



-- 

Trevor Barstow

[image: Mobile5 Media Ltd] <http://mobile-5.com/>

Mobile5 Media Ltd
16 Dufour's Place, W1F 7SP
t: +44 (0)1234 567891
m: +44 (0)1234 567891
Skype: mobile5.trevor.barstow
http://mobile-5.com

[image: Mobile5 Media Ltd]  <https://twitter.com/mobilefive>[image: Mobile5
Media Ltd]  <https://www.linkedin.com/company/mobile5-media-limited>[image:
Mobile5 Media Ltd] <https://www.facebook.com/mobile5media>


This e-mail and any accompanying attachments are intended only to be read
or used by the named addressee(s). It is confidential and contains legally
privileged information. If you have received this message in error, please
notify the sender immediately and delete this message.

**Comment by onovotny** [comment]
.NET Native issues can be tough to figure out :(

Can you look at the obj\Release\ilc\in directory to see what files are there, are all of the expected metrolog ones there?

How about any detailed/diagnostic level build logs to see what might be going on with the file copies?

One way to narrow this down and rule things out is to create a new dummy blank app, add metrolog, add a few log statements and compile it in release mode to verify it works.

**Comment by TrevorBarstowMobile5** [comment]
>>>One way to narrow this down and rule things out is to create a new dummy blank app, add metrolog, add a few log statements and compile it in release mode to verify it works.
The test app works ok.

>>>Can you look at the obj\Release\ilc\in directory to see what files are there, are all of the expected metrolog ones there?
What should I expect to see in obj\Release\ilc\in directory ?  I am seeing these items in both test app which works and main app that doesn't:-
MetroLog.dll
MetroLog.Platform.dll
MetroLog.WinRT.winmd

**Comment by TrevorBarstowMobile5** [comment]
Just to let you know I have managed to get things working. The existing solution was converted from Windows 8.1 rather than create a new UWP solution and add existing source files in. 

I recreated the solution from scratch and so far things seem to be working ok.
Thanks for your help and pointers.

Regards
Trevor

**Comment by onovotny** [comment]
Glad that it works! At some point, it might be worth diffing the csproj files to see what the differences were/are. If there's a bug in the project upgrade mechanism then I can let them know.

**Comment by atslughorn** [comment]
I just had the same issue. It wasn't the project file but rather the rd.xml. In my case I had one suitable for a class library (my mistake - I was manually upgrading). There is a special one for the application looking like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="*Application*" Dynamic="Required All" />
    <!-- add directives for your library here -->
  </Application>
</Directives>
```
Fixing this file solved the issue for me.

**Comment by onovotny** [comment]
Closing this as it appears resolved. Please reopen if there's still an issue.
